// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Seb4Vision.CSportView.Data;
using System;

namespace Seb4Vision.CSportView.Data.Migrations
{
    [DbContext(typeof(Seb4VisionCSportViewContext))]
    [Migration("20180716175801_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Seb4Vision.CSportView.Data.Model.MatchStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("TeamAStatsId");

                    b.Property<int?>("TeamBStatsId");

                    b.HasKey("Id");

                    b.HasIndex("TeamAStatsId");

                    b.HasIndex("TeamBStatsId");

                    b.ToTable("MatchStats");
                });

            modelBuilder.Entity("Seb4Vision.CSportView.Data.Model.TeamMatchStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Corners");

                    b.Property<int>("Fouls");

                    b.Property<int>("Goals");

                    b.Property<int>("Injuries");

                    b.Property<int>("Offsides");

                    b.Property<decimal>("PassAccuracy");

                    b.Property<decimal>("Possession");

                    b.Property<int>("RedCards");

                    b.Property<decimal>("ShotAccuracy");

                    b.Property<int>("Shots");

                    b.Property<int>("ShotsOnTarget");

                    b.Property<int>("Tackles");

                    b.Property<int>("TeamId");

                    b.Property<int>("YellowCards");

                    b.HasKey("Id");

                    b.ToTable("TeamMatchStats");
                });

            modelBuilder.Entity("Seb4Vision.CSportView.Data.Model.MatchStats", b =>
                {
                    b.HasOne("Seb4Vision.CSportView.Data.Model.TeamMatchStats", "TeamAStats")
                        .WithMany()
                        .HasForeignKey("TeamAStatsId");

                    b.HasOne("Seb4Vision.CSportView.Data.Model.TeamMatchStats", "TeamBStats")
                        .WithMany()
                        .HasForeignKey("TeamBStatsId");
                });
#pragma warning restore 612, 618
        }
    }
}
